// Code generated by tygo. DO NOT EDIT.

//////////
// source: acled.go

/**
 * DisorderType represents the three broad categories of disorder in ACLED data
 */
export const DisorderTypePoliticalViolence = "Political violence";
export const DisorderTypeDemonstrations = "Demonstrations";
export const DisorderTypeStrategic = "Strategic developments";
export type DisorderType = typeof DisorderTypePoliticalViolence | typeof DisorderTypeDemonstrations | typeof DisorderTypeStrategic;
/**
 * EventType represents the six main event classifications in ACLED data
 */
export const EventTypeBattles = "Battles";
export const EventTypeProtests = "Protests";
export const EventTypeRiots = "Riots";
export const EventTypeExplosionsRemoteViolence = "Explosions/Remote violence";
export const EventTypeViolenceAgainstCivilians = "Violence against civilians";
export const EventTypeStrategicDevelopments = "Strategic developments";
export type EventType = typeof EventTypeBattles | typeof EventTypeProtests | typeof EventTypeRiots | typeof EventTypeExplosionsRemoteViolence | typeof EventTypeViolenceAgainstCivilians | typeof EventTypeStrategicDevelopments;
/**
 * SubEventType is the most detailed event type classification level
 */
/**
 * Battles
 */
export const SubEventTypeBattlesGovernmentRegainsTerritory = "Government regains territory";
export const SubEventTypeBattlesNonStateActorOvertakesTerritory = "Non-state actor overtakes territory";
export const SubEventTypeBattlesArmedClash = "Armed clash";
/**
 * Protests
 */
export const SubEventTypeProtestsExcessiveForceAgainstProtesters = "Excessive force against protesters";
export const SubEventTypeProtestsProtestWithIntervention = "Protest with intervention";
export const SubEventTypeProtestsPeacefulProtest = "Peaceful protest";
/**
 * Riots
 */
export const SubEventTypeRiotsViolentDemonstration = "Violent demonstration";
export const SubEventTypeRiotsMobViolence = "Mob violence";
/**
 * Explosions/Remote violence
 */
export const SubEventTypeExplosionsChemicalWeapon = "Chemical weapon";
export const SubEventTypeExplosionsAirDroneStrike = "Air/drone strike";
export const SubEventTypeExplosionsSuicideBomb = "Suicide bomb";
export const SubEventTypeExplosionsShellingArtilleryMissile = "Shelling/artillery/missile attack";
export const SubEventTypeExplosionsRemoteExplosiveLandmineIED = "Remote explosive/landmine/IED";
export const SubEventTypeExplosionsGrenade = "Grenade";
/**
 * Violence against civilians
 */
export const SubEventTypeVACiviliansSexualViolence = "Sexual violence";
export const SubEventTypeVACiviliansAttack = "Attack";
export const SubEventTypeVACiviliansAbductionForcedDisappear = "Abduction/forced disappearance";
/**
 * Strategic developments
 */
export const SubEventTypeStrategicAgreement = "Agreement";
export const SubEventTypeStrategicArrests = "Arrests";
export const SubEventTypeStrategicChangeToGroupActivity = "Change to group/activity";
export const SubEventTypeStrategicDisruptedWeaponsUse = "Disrupted weapons use";
export const SubEventTypeStrategicHeadquartersOrBaseEstablished = "Headquarters or base established";
export const SubEventTypeStrategicLootingPropertyDestruction = "Looting/property destruction";
export const SubEventTypeStrategicNonViolentTransferOfTerritory = "Non-violent transfer of territory";
export const SubEventTypeStrategicOther = "Other";
export type SubEventType = typeof SubEventTypeBattlesGovernmentRegainsTerritory | typeof SubEventTypeBattlesNonStateActorOvertakesTerritory | typeof SubEventTypeBattlesArmedClash | typeof SubEventTypeProtestsExcessiveForceAgainstProtesters | typeof SubEventTypeProtestsProtestWithIntervention | typeof SubEventTypeProtestsPeacefulProtest | typeof SubEventTypeRiotsViolentDemonstration | typeof SubEventTypeRiotsMobViolence | typeof SubEventTypeExplosionsChemicalWeapon | typeof SubEventTypeExplosionsAirDroneStrike | typeof SubEventTypeExplosionsSuicideBomb | typeof SubEventTypeExplosionsShellingArtilleryMissile | typeof SubEventTypeExplosionsRemoteExplosiveLandmineIED | typeof SubEventTypeExplosionsGrenade | typeof SubEventTypeVACiviliansSexualViolence | typeof SubEventTypeVACiviliansAttack | typeof SubEventTypeVACiviliansAbductionForcedDisappear | typeof SubEventTypeStrategicAgreement | typeof SubEventTypeStrategicArrests | typeof SubEventTypeStrategicChangeToGroupActivity | typeof SubEventTypeStrategicDisruptedWeaponsUse | typeof SubEventTypeStrategicHeadquartersOrBaseEstablished | typeof SubEventTypeStrategicLootingPropertyDestruction | typeof SubEventTypeStrategicNonViolentTransferOfTerritory | typeof SubEventTypeStrategicOther;
/**
 * GeographicAreaType represents the type of a geographic area
 */
export const GeographicAreaTypeRegion = "region";
export const GeographicAreaTypeCountry = "country";
export const GeographicAreaTypeAdmin1 = "admin_1";
export type GeographicAreaType = typeof GeographicAreaTypeRegion | typeof GeographicAreaTypeCountry | typeof GeographicAreaTypeAdmin1;
/**
 * GeographicArea represents a row from the geographic_area table
 */
export interface GeographicArea {
	id: number /* int */;
	acled_code?: number /* int */;
	name: string;
	type: GeographicAreaType;
	iso?: string;
	parent?: number /* int */;
	geojson?: any;
}
/**
 * ACLEDWeeklyAggregateBase contains the common fields for all aggregated ACLED data
 */
export interface ACLEDWeeklyAggregateBase {
	/**
	 * Week is the date of the Saturday marking the start of that week of aggregated data (Saturday to Friday)
	 */
	week: string /* RFC3339 */;
	/**
	 * RegionID is the foreign key referencing the region in the geographic_area table
	 */
	region_id: number /* int */;
	/**
	 * CountryID is the foreign key referencing the country in the geographic_area table
	 */
	country_id?: number /* int */;
	/**
	 * Admin1ID is the foreign key referencing the admin1 area in the geographic_area table
	 */
	admin1_id?: number /* int */;
	/**
	 * DisorderType is one of three broad categories: Political violence, Demonstrations, or Strategic developments
	 */
	disorder_type: DisorderType;
	/**
	 * EventType is one of six main event classifications
	 */
	event_type: EventType;
	/**
	 * SubEventType is the most detailed event type classification level
	 */
	sub_event_type: SubEventType;
	/**
	 * EventCount is the total number of discrete events recorded for the specified week, Admin1, and sub_event_type
	 */
	event_count: number /* uint64 */;
	/**
	 * Fatalities is the sum of reported fatalities across the events for this row
	 */
	fatalities: number /* uint64 */;
	/**
	 * PopulationExposure is the best aggregated estimate of people exposed to any events that week
	 * NOTE: Users should not sum these values as they represent exposure estimates based on proximity
	 */
	population_exposure: number /* uint64 */;
	/**
	 * CentroidLongitude is the longitude of the geographic center point for mapping the administrative district
	 */
	centroid_longitude: number /* float64 */;
	/**
	 * CentroidLatitude is the latitude of the geographic center point for mapping the administrative district
	 */
	centroid_latitude: number /* float64 */;
}
/**
 * ACLEDWeeklyAggregate is an alias for ACLEDWeeklyAggregateBase
 */
export type ACLEDWeeklyAggregate = ACLEDWeeklyAggregateBase;
