// Code generated by tygo. DO NOT EDIT.

//////////
// source: acled.go

/**
 * DisorderType represents the three broad categories of disorder in ACLED data
 */
export const DisorderTypePoliticalViolence = "Political violence";
export const DisorderTypeDemonstrations = "Demonstrations";
export const DisorderTypeStrategic = "Strategic developments";
export type DisorderType = typeof DisorderTypePoliticalViolence | typeof DisorderTypeDemonstrations | typeof DisorderTypeStrategic;
/**
 * EventType represents the six main event classifications in ACLED data
 */
export const EventTypeBattles = "Battles";
export const EventTypeProtests = "Protests";
export const EventTypeRiots = "Riots";
export const EventTypeExplosionsRemoteViolence = "Explosions/Remote violence";
export const EventTypeViolenceAgainstCivilians = "Violence against civilians";
export const EventTypeStrategicDevelopments = "Strategic developments";
export type EventType = typeof EventTypeBattles | typeof EventTypeProtests | typeof EventTypeRiots | typeof EventTypeExplosionsRemoteViolence | typeof EventTypeViolenceAgainstCivilians | typeof EventTypeStrategicDevelopments;
/**
 * SubEventType is a marker interface that all sub-event types must implement
 */
export type SubEventType = any;
/**
 * Battles sub-event types
 */
export type BattlesSubEventType = string;
export const BattlesGovernmentRegainsTerritory: BattlesSubEventType = "Government regains territory";
export const BattlesNonStateActorOvertakesTerritory: BattlesSubEventType = "Non-state actor overtakes territory";
export const BattlesArmedClash: BattlesSubEventType = "Armed clash";
/**
 * Protests sub-event types
 */
export type ProtestsSubEventType = string;
export const ProtestsExcessiveForceAgainstProtesters: ProtestsSubEventType = "Excessive force against protesters";
export const ProtestsProtestWithIntervention: ProtestsSubEventType = "Protest with intervention";
export const ProtestsPeacefulProtest: ProtestsSubEventType = "Peaceful protest";
/**
 * Riots sub-event types
 */
export type RiotsSubEventType = string;
export const RiotsViolentDemonstration: RiotsSubEventType = "Violent demonstration";
export const RiotsMobViolence: RiotsSubEventType = "Mob violence";
/**
 * Explosions/Remote violence sub-event types
 */
export type ExplosionsRemoteViolenceSubEventType = string;
export const ExplosionsRemoteViolenceChemicalWeapon: ExplosionsRemoteViolenceSubEventType = "Chemical weapon";
export const ExplosionsRemoteViolenceAirDroneStrike: ExplosionsRemoteViolenceSubEventType = "Air/drone strike";
export const ExplosionsRemoteViolenceSuicideBomb: ExplosionsRemoteViolenceSubEventType = "Suicide bomb";
export const ExplosionsRemoteViolenceShellingArtilleryMissile: ExplosionsRemoteViolenceSubEventType = "Shelling/artillery/missile attack";
export const ExplosionsRemoteViolenceRemoteExplosiveLandmineIED: ExplosionsRemoteViolenceSubEventType = "Remote explosive/landmine/IED";
export const ExplosionsRemoteViolenceGrenade: ExplosionsRemoteViolenceSubEventType = "Grenade";
/**
 * Violence against civilians sub-event types
 */
export type ViolenceAgainstCiviliansSubEventType = string;
export const ViolenceAgainstCiviliansSexualViolence: ViolenceAgainstCiviliansSubEventType = "Sexual violence";
export const ViolenceAgainstCiviliansAttack: ViolenceAgainstCiviliansSubEventType = "Attack";
export const ViolenceAgainstCiviliansAbductionForcedDisappear: ViolenceAgainstCiviliansSubEventType = "Abduction/forced disappearance";
/**
 * Strategic developments sub-event types
 */
export type StrategicDevelopmentsSubEventType = string;
export const StrategicDevelopmentsAgreement: StrategicDevelopmentsSubEventType = "Agreement";
export const StrategicDevelopmentsArrests: StrategicDevelopmentsSubEventType = "Arrests";
export const StrategicDevelopmentsChangeToGroupActivity: StrategicDevelopmentsSubEventType = "Change to group/activity";
export const StrategicDevelopmentsDisruptedWeaponsUse: StrategicDevelopmentsSubEventType = "Disrupted weapons use";
export const StrategicDevelopmentsHeadquartersOrBaseEstablished: StrategicDevelopmentsSubEventType = "Headquarters or base established";
export const StrategicDevelopmentsLootingPropertyDestruction: StrategicDevelopmentsSubEventType = "Looting/property destruction";
export const StrategicDevelopmentsNonViolentTransferOfTerritory: StrategicDevelopmentsSubEventType = "Non-violent transfer of territory";
export const StrategicDevelopmentsOther: StrategicDevelopmentsSubEventType = "Other";
/**
 * Region represents ACLED's broad geographic classifications
 */
export const RegionMiddleEast = "Middle East";
export const RegionSouthAsia = "South Asia";
export const RegionSoutheastAsia = "Southeast Asia";
export const RegionEastAsia = "East Asia";
export const RegionCentralAsia = "Central Asia";
export const RegionCaucasus = "Caucasus and Central Asia";
export const RegionEasternAfrica = "Eastern Africa";
export const RegionMiddleAfrica = "Middle Africa";
export const RegionSouthernAfrica = "Southern Africa";
export const RegionWesternAfrica = "Western Africa";
export const RegionEasternEurope = "Eastern Europe";
export const RegionSoutheasternEurope = "Southeastern Europe";
export const RegionWesternEurope = "Western Europe";
export const RegionNorthAmerica = "North America";
export const RegionCentralAmerica = "Central America";
export const RegionSouthAmerica = "South America";
export const RegionCaribbean = "Caribbean";
export const RegionOceania = "Oceania";
export type Region = typeof RegionMiddleEast | typeof RegionSouthAsia | typeof RegionSoutheastAsia | typeof RegionEastAsia | typeof RegionCentralAsia | typeof RegionCaucasus | typeof RegionEasternAfrica | typeof RegionMiddleAfrica | typeof RegionSouthernAfrica | typeof RegionWesternAfrica | typeof RegionEasternEurope | typeof RegionSoutheasternEurope | typeof RegionWesternEurope | typeof RegionNorthAmerica | typeof RegionCentralAmerica | typeof RegionSouthAmerica | typeof RegionCaribbean | typeof RegionOceania;
/**
 * ACLEDWeeklyAggregateBase contains the common fields for all aggregated ACLED data
 */
export interface ACLEDWeeklyAggregateBase {
	/**
	 * Week is the date of the Saturday marking the start of that week of aggregated data (Saturday to Friday)
	 */
	week: string /* RFC3339 */;
	/**
	 * Region is the broad geographic classification
	 */
	region: Region;
	/**
	 * Country is the country or territory identifier
	 */
	country: string;
	/**
	 * Admin1 is the first-order administrative division (state, province, department, etc.)
	 */
	admin1: string;
	/**
	 * DisorderType is one of three broad categories: Political violence, Demonstrations, or Strategic developments
	 */
	disorder_type: DisorderType;
	/**
	 * EventType is one of six main event classifications
	 */
	event_type: EventType;
	/**
	 * SubEventType is the most detailed event type classification level
	 * This will be one of the concrete sub-event types (BattlesSubEventType, RiotsSubEventType, etc.)
	 */
	sub_event_type: SubEventType;
	/**
	 * Events is the total number of discrete events recorded for the specified week, Admin1, and sub_event_type
	 */
	events: number /* uint64 */;
	/**
	 * Fatalities is the sum of reported fatalities across the events for this row
	 */
	fatalities: number /* uint64 */;
	/**
	 * PopulationBest is the best aggregated estimate of people exposed to any events that week
	 * NOTE: Users should not sum these values as they represent exposure estimates based on proximity
	 */
	population_best: number /* uint64 */;
	/**
	 * CentroidLongitude is the longitude of the geographic center point for mapping the administrative district
	 */
	centroid_longitude: number /* float64 */;
	/**
	 * CentroidLatitude is the latitude of the geographic center point for mapping the administrative district
	 */
	centroid_latitude: number /* float64 */;
}
/**
 * BattlesAggregate ensures SubEventType can only be a BattlesSubEventType
 */
export interface BattlesAggregate {
	ACLEDWeeklyAggregateBase: ACLEDWeeklyAggregateBase;
}
/**
 * ProtestsAggregate ensures SubEventType can only be a ProtestsSubEventType
 */
export interface ProtestsAggregate {
	ACLEDWeeklyAggregateBase: ACLEDWeeklyAggregateBase;
}
/**
 * RiotsAggregate ensures SubEventType can only be a RiotsSubEventType
 */
export interface RiotsAggregate {
	ACLEDWeeklyAggregateBase: ACLEDWeeklyAggregateBase;
}
/**
 * ExplosionsRemoteViolenceAggregate ensures SubEventType can only be an ExplosionsRemoteViolenceSubEventType
 */
export interface ExplosionsRemoteViolenceAggregate {
	ACLEDWeeklyAggregateBase: ACLEDWeeklyAggregateBase;
}
/**
 * ViolenceAgainstCiviliansAggregate ensures SubEventType can only be a ViolenceAgainstCiviliansSubEventType
 */
export interface ViolenceAgainstCiviliansAggregate {
	ACLEDWeeklyAggregateBase: ACLEDWeeklyAggregateBase;
}
/**
 * StrategicDevelopmentsAggregate ensures SubEventType can only be a StrategicDevelopmentsSubEventType
 */
export interface StrategicDevelopmentsAggregate {
	ACLEDWeeklyAggregateBase: ACLEDWeeklyAggregateBase;
}
/**
 * ACLEDWeeklyAggregate is an alias for ACLEDWeeklyAggregateBase for backwards compatibility
 * and to make it clear when you're working with the base type directly
 */
export type ACLEDWeeklyAggregate = ACLEDWeeklyAggregateBase;
