// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 *  ***************************
 *  * * ACLED CUSTOM DATA TYPES *
 *  * ***************************
 */
export type DisorderType = string;
export const Demonstrations: DisorderType = "Demonstrations";
export const PoliticalViolence: DisorderType = "Political violence";
export const PoliticalViolenceDemonstrations: DisorderType = "Political violence; Demonstrations";
export const StrategicDevelopments: DisorderType = "Strategic developments";
export type EventType = string;
export const Battles: EventType = "Battles";
export const Protests: EventType = "Protests";
export const Riots: EventType = "Riots";
export const ExplosionsRemoteViolence: EventType = "Explosions / Remote violence";
export const ViolenceAgainstCivilians: EventType = "Violence against civilians";
export const StrategicDevelopmentsEvent: EventType = "Strategic developments";
export type SubEventType = string;
export const GovernmentRegainsTerritory: SubEventType = "Government regains territory";
export const NonStateActorOvertakesTerritory: SubEventType = "Non-state actor overtakes territory";
export const ArmedClash: SubEventType = "Armed clash";
/**
 * https://acleddata.com/faq-codebook-tools#acleds-aggregated-data-0
 */
export interface ACLEDWeeklyAggregate {
	week: number /* int64 */;
	/**
	 * TODO make this an enum
	 */
	region: string;
	country: string;
	admin1: string;
	disorderType: DisorderType;
	eventType: EventType;
	subEventType: SubEventType;
	eventCount: number /* uint64 */;
	fatalityCount: number /* uint64 */;
	populationExposure: number /* uint64 */;
}
