CREATE TABLE IF NOT EXISTS region (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
	acled_code INTEGER 
);

CREATE TABLE IF NOT EXISTS interaction (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name TEXT UNIQUE NOT NULL,
	acled_code INTEGER
);